FROM node:18

COPY ./package.json /wanted-pre-onboarding/
COPY ./package-lock.json /wanted-pre-onboarding/
WORKDIR /wanted-pre-onboarding/
RUN npm install

COPY . /wanted-pre-onboarding/
CMD npm run start:dev
