version: '3.7'

services:
    api:
        build:
            context: .
            dockerfile: DockerFile
        volumes:
            - ./src:/api/src
        restart: always
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}

    dev_db:
        image: mysql:8
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME} # 데이터베이스 이름
            MYSQL_ROOT_USER: ${DATABASE_ROOT_USER} # root 유저
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD} # root 유저 비밀번호
        restart: always
        ports:
            - ${DATABASE_PORT}:${DATABASE_PORT}
