services:
    api:
        build:
            context: .
            dockerfile: DockerFile
        volumes:
            - ./src:/api/src
        restart: always
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        depends_on:
            dev_db:
                condition: service_healthy
        networks:
            - container-network

    dev_db:
        image: mysql:latest
        container_name: db
        environment:
            MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        restart: always
        ports:
            - ${MYSQL_PORT}:${MYSQL_PORT}
        networks:
            - container-network
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
            timeout: 20s
            retries: 10
networks:
    container-network:
        driver: bridge
